class CfgVehicles {
	class Box_MEU_Weapons;
	class Box_MEU_Items_USMC: Box_MEU_Items {
	    class TransportItems {
	    	MACRO_ADDITEM(A3_GPNVG18_F,10);
	    	MACRO_ADDITEM(A3_GPNVG18_BLK_F,10);
	    	MACRO_ADDITEM(A3_GPNVG18b_F,10);
	    	MACRO_ADDITEM(A3_GPNVG18b_BLK_F,10);
	    	MACRO_ADDITEM(A3_GPNVG18_REC_F,10);
	    	MACRO_ADDITEM(A3_GPNVG18_REC_BLK_F,10);
	    	MACRO_ADDITEM(A3_GPNVG18b_REC_F,10);
	    	MACRO_ADDITEM(A3_GPNVG18b_REC_BLK_F,10);
	    };
	};
};