class CfgVehicles {
	class Box_MEU_Weapons;
	class Box_MEU_Weapons_USMC: Box_MEU_Weapons {	
	    class TransportWeapons {
	    	MACRO_ADDWEAPON(RHARD_MK18_F,10);
	    	MACRO_ADDWEAPON(RHARD_MK18D_F,10);
	    	MACRO_ADDWEAPON(RHARD_MK18PD_F,10);
	    	MACRO_ADDWEAPON(RHARD_MK18AFG_F,10);
	    	MACRO_ADDWEAPON(RHARD_MK18AFGD_F,10);
	    	MACRO_ADDWEAPON(RHARD_MK18AFG_B_F,10);
	    	MACRO_ADDWEAPON(RHARD_MK18AFGD_B_F,10);
	    	MACRO_ADDWEAPON(RHARD_MK18E_F,10);
	    	MACRO_ADDWEAPON(RHARD_MK18ED_F,10);
	    	MACRO_ADDWEAPON(RHARD_M4DDR_F,10);
	    	MACRO_ADDWEAPON(RHARD_M4DDRD_F,10);
	    	MACRO_ADDWEAPON(RHARD_M4DDR_B_F,10);
	    	MACRO_ADDWEAPON(RHARD_M4DDRD_B_F,10);
	    	MACRO_ADDWEAPON(RHARD_M4DDRP_F,10);
	    	MACRO_ADDWEAPON(RHARD_M4DDRPD_F,10);
	    	MACRO_ADDWEAPON(RHARD_M4DDRGL_F,10);
	    	MACRO_ADDWEAPON(RHARD_M4DDRGLD_F,10);
	    	MACRO_ADDWEAPON(RHARD_M4DDRGL_B_F,10);
	    	MACRO_ADDWEAPON(RHARD_M4DDRGLD_B_F,10);
	    };
	};
};